### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by mershark** [mershark/ruby-group-capstone#25]
1. Link to project
[Click here](https://github.com/users/mershark/projects/7/views/1)

2. This project consist of 4 team members

3. Below is a list of team members and their respective numbers:
    - Team member 1 @mershark 
    - Team member 2 @Mike47ip 
    - Team member 3 @fatmahussein 
    - Team member 4 @prg-04

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Please make sure that all tasks are equally distributed between all team members as per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=no%20single%20person%20should%20be%20doing%20all%20of%20the%20most%20time%2Dconsuming%20tasks). No team member should have `5pt` more than others.

- [ ] Kindly add a description for the following task:
   - [ ] https://github.com/mershark/ruby-group-capstone/issues/10
as per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). All tasks should have a description.
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mershark** [comment]
thank you @Ibizugbe i think theres a filter input so it filters out and show only one team member so when you remove it, it shows the other team members please, if you could kindly check

![image](https://github.com/mershark/ruby-group-capstone/assets/113654948/446a20b5-c02e-4d86-8b61-3826913de29b)

**Comment by mershark** [comment]
Alright, Thank you @nicupop729

**Comment by iambenkis** [comment]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

-  A description for the unit test task has been added :heavy_check_mark: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
